print("merhaba")
print("benim adım Mahmut")
print("Python hikayeme hoşgeldin")
print("bu benim",1,". programım")
print("peki senin adın nedir ?")
input()
print("seninle tanıştığıma memnun oldum")
print("programımı kullandığın için teşekkürler")
input()
