sayi = int(input("Bir Sayı Giriniz : "))
islem1 = sayi*int(input("kaç katı : "))
# print(islem1)
islem2 = islem1 - int(input("Kaç Eksiği : "))
# print(islem2)
islem3 = islem2 / int(input("Kaça Bölümü : "))
# print(islem3)
islem4 = islem3 + int(input("Kaç Fazlası : "))
print("sonucu gösterelerim mi ?")
input()
print(islem4)